=== looost/Epam_final_project/task13/src/main/resources/xml/serials.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/serials"
        xmlns:tns="http://www.training.by/serials"
        elementFormDefault="qualified">
    <element name="serials">
        <complexType>
            <sequence>
                <element name="serial"
                         type="tns:Serial"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Serial">
        <sequence>
            <element name="name" type="string"/>
            <element name="description" type="string"/>
            <element name="logo" type="string"/>
            <element name="fullLogo" type="string"/>
            <element name="releaseDate" type="date"/>
            <element name="countLike" type="int" default="0"/>
            <element name="country" type="tns:Country"/>
            <element name="studio" type="tns:Studio"/>
            <element name="genres" type="tns:Genres"/>
            <element name="comments" type="tns:Comments"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>
    <complexType name="Country">
        <sequence>
            <element name="name" type="string"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>

    <complexType name="Studio">
        <sequence>
            <element name="name" type="string"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>

    <complexType name="Genres">
        <sequence>
            <element name="genre" type="tns:Genre" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Comments">
        <sequence>
            <element name="comment" type="tns:Comment" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Genre">
        <sequence>
            <element name="name" type="string"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>

    <complexType name="Comment">
        <sequence>
            <element name="user" type="tns:User"/>
            <element name="comment-text" type="string"/>
            <element name="publicationDate" type="date"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>

    <complexType name="User">
        <sequence>
            <element name="login" type="string"/>
            <element name="password" type="string"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
        <attribute name="role" use="required">
            <simpleType>
                <restriction base="int">
                    <enumeration value="1"/>
                    <enumeration value="2"/>
                    <enumeration value="3"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>


</schema>

=== looost/Epam_final_project/task13/src/main/resources/xml/serials.xml
<?xml version="1.0" encoding="UTF-8" ?>


<serials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.training.by/serials"
         xsi:schemaLocation="http://www.example.com/students serials.xsd">

    <serial id="0">

        <name>Dark</name>

        <description>Description .....................</description>

        <logo>img/dark.jpg</logo>

        <fullLogo>img/dark_full.jpg</fullLogo>

        <releaseDate>2017-12-01</releaseDate>

        <countLike>0</countLike>

        <country id="0">
            <name>USA</name>
        </country>

        <studio id="0">
            <name>HBO</name>
        </studio>

        <genres>
            <genre id="0">
                <name>Drama</name>
            </genre>
            <genre id="1">
                <name>Crime</name>
            </genre>
            <genre id="2">
                <name>Mystery</name>
            </genre>
        </genres>

        <comments>
            <comment id="1">
                <user id="0" role="3">
                    <login>user</login>
                    <password>password</password>
                </user>
                <comment-text>Комментарий .............</comment-text>
                <publicationDate>2019-01-20</publicationDate>
            </comment>
            <comment id="2">
                <user id="1" role="2">
                    <login>admin</login>
                    <password>password</password>
                </user>
                <comment-text>Комментарий 22222222 .............</comment-text>
                <publicationDate>2019-02-01</publicationDate>
            </comment>
            <comment id="3">
                <user id="0" role="3">
                    <login>user</login>
                    <password>password</password>
                </user>
                <comment-text>Комментарий adfsadfsdf sdf sdf .............</comment-text>
                <publicationDate>2019-12-13</publicationDate>
            </comment>
        </comments>

    </serial>

    <serial id="1">

        <name>La Casa de Papel</name>

        <description>История о преступниках, решивших ограбить Королевский монетный двор Испании и украсть 2,4 млрд
            евро.
        </description>

        <logo>img/papel.jpg</logo>

        <fullLogo>img/lcdp_full.jpg</fullLogo>

        <releaseDate>2017-05-02</releaseDate>

        <countLike>0</countLike>

        <country id="3">
            <name>Spain</name>
        </country>

        <studio id="3">
            <name>Channel 3</name>
        </studio>

        <genres>
            <genre id="1">
                <name>Crime</name>
            </genre>
        </genres>

        <comments>
            <comment id="4">
                <user id="2" role="2">
                    <login>moder</login>
                    <password>123456</password>
                </user>
                <comment-text>Кооментарий</comment-text>
                <publicationDate>2019-02-13</publicationDate>
            </comment>
        </comments>

    </serial>
</serials>
